// SPDX-License-Identifier: AGPL-3.0-or-later
import type { PartGraph } from '@furniture/contracts';
import type { FabricationExporter } from './index';

export interface PrintOptions { scale?: 20 | 25 | 50; minWallMm?: number; }
const faces = [[0, 1, 2], [2, 3, 0], [4, 6, 5], [6, 4, 7], [0, 4, 5], [5, 1, 0], [1, 5, 6], [6, 2, 1], [2, 6, 7], [7, 3, 2], [4, 0, 3], [3, 7, 4]];
export const print3mfExporter: FabricationExporter<PrintOptions> = {
  id: 'print-3mf',
  validate(graph, options) { const scale = options.scale ?? 25; return graph.parts.flatMap((part) => Math.max(part.size.length, part.size.width) / scale > 210 ? [`${part.id}: scaled model exceeds a conservative 220 mm printer bed.`] : []); },
  export(graph, options) {
    const scale = options.scale ?? 25, minWall = options.minWallMm ?? 1; let id = 1; const objects: string[] = [];
    for (const part of graph.parts) for (let n = 0; n < part.qty; n += 1) { const x = part.size.length / scale, y = part.size.width / scale, z = Math.max(part.size.thickness / scale, minWall); const vertices = [[0, 0, 0], [x, 0, 0], [x, y, 0], [0, y, 0], [0, 0, z], [x, 0, z], [x, y, z], [0, y, z]].map((v) => `<vertex x="${v[0]}" y="${v[1]}" z="${v[2]}"/>`).join(''); const triangles = faces.map((f) => `<triangle v1="${f[0]}" v2="${f[1]}" v3="${f[2]}"/>`).join(''); objects.push(`<object id="${id}" type="model" name="${part.id}${part.qty > 1 ? `.${n + 1}` : ''}"><mesh><vertices>${vertices}</vertices><triangles>${triangles}</triangles></mesh></object>`); id += 1; }
    const model = `<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"><resources>${objects.join('')}</resources><build>${Array.from({ length: id - 1 }, (_, i) => `<item objectid="${i + 1}"/>`).join('')}</build></model>`;
    const zip = zipStore({ '[Content_Types].xml': '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>', '_rels/.rels': '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>', '3D/3dmodel.model': model });
    return { files: [{ filename: `prototype_${graph.source.projectId}_1-${scale}.3mf`, mimeType: 'model/3mf', content: base64(zip), encoding: 'base64' }], warnings: ['Outer envelope is true scale; thin panels are thickened inward to the configured printable wall thickness.'] };
  },
};
function zipStore(files: Record<string, string>): Uint8Array { const encoded = Object.entries(files).map(([name, content]) => ({ name, nameBytes: utf8(name), bytes: utf8(content) })); let offset = 0; const locals = encoded.map((file) => { const out = new Uint8Array(30 + file.nameBytes.length + file.bytes.length); const v = new DataView(out.buffer); v.setUint32(0, 0x04034b50, true); v.setUint16(4, 20, true); v.setUint32(14, crc32(file.bytes), true); v.setUint32(18, file.bytes.length, true); v.setUint32(22, file.bytes.length, true); v.setUint16(26, file.nameBytes.length, true); out.set(file.nameBytes, 30); out.set(file.bytes, 30 + file.nameBytes.length); const result = { out, offset }; offset += out.length; return result; }); const central = encoded.map((file, i) => { const out = new Uint8Array(46 + file.nameBytes.length); const v = new DataView(out.buffer); v.setUint32(0, 0x02014b50, true); v.setUint16(4, 20, true); v.setUint16(6, 20, true); v.setUint32(16, crc32(file.bytes), true); v.setUint32(20, file.bytes.length, true); v.setUint32(24, file.bytes.length, true); v.setUint16(28, file.nameBytes.length, true); v.setUint32(42, locals[i].offset, true); out.set(file.nameBytes, 46); return out; }); const centralSize = central.reduce((n, value) => n + value.length, 0); const out = new Uint8Array(offset + centralSize + 22); let at = 0; for (const local of locals) { out.set(local.out, at); at += local.out.length; } for (const entry of central) { out.set(entry, at); at += entry.length; } const view = new DataView(out.buffer); view.setUint32(at, 0x06054b50, true); view.setUint16(at + 8, encoded.length, true); view.setUint16(at + 10, encoded.length, true); view.setUint32(at + 12, centralSize, true); view.setUint32(at + 16, offset, true); return out; }
function utf8(value: string) { return new Uint8Array(unescape(encodeURIComponent(value)).split('').map((c) => c.charCodeAt(0))); }
function crc32(bytes: Uint8Array) { let crc = -1; for (const byte of bytes) { crc ^= byte; for (let k = 0; k < 8; k += 1) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1)); } return (crc ^ -1) >>> 0; }
function base64(bytes: Uint8Array) { const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'; let out = ''; for (let i = 0; i < bytes.length; i += 3) { const a = bytes[i], b = bytes[i + 1], c = bytes[i + 2]; out += alphabet[a >> 2] + alphabet[((a & 3) << 4) | ((b ?? 0) >> 4)] + (b === undefined ? '=' : alphabet[((b & 15) << 2) | ((c ?? 0) >> 6)]) + (c === undefined ? '=' : alphabet[c & 63]); } return out; }
